s = set()
# print(type(s))
# s_from_list = set([1, 2, 3, 4])
# print(s_from_list)
# print(type(s_from_list))
s.add(1)
s.add(2)
s.add(3)

s1 = s.union({4, 5, 6})
s.remove(2)
# s1 = s.intersection({4, 1, 3})
# s1 = {7, 8}
# print(s.isdisjoint(s1))
# print(s, s1)
# print(len(s))
# print(min(s))
# print(max(s1))
print(s, s1)
